import { BookOpen, Leaf, Sparkles } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";
import * as ScrollArea from "@radix-ui/react-scroll-area";
import * as Tooltip from "@radix-ui/react-tooltip";
import { cn } from "@/lib/utils";

export type ShellScreen = "setup" | "past" | "mascotLibrary";
const items: Array<{ screen: ShellScreen; label: string; icon: typeof Leaf }> = [{ screen: "setup", label: "Start", icon: Leaf }, { screen: "past", label: "Sessions", icon: BookOpen }, { screen: "mascotLibrary", label: "Mascot", icon: Sparkles }];

export function AppShell({ screen, onNavigate, children }: React.PropsWithChildren<{ screen: ShellScreen; onNavigate: (screen: ShellScreen) => void }>): React.JSX.Element {
  const reduceMotion = useReducedMotion();
  return <Tooltip.Provider delayDuration={350}><main className="min-h-screen bg-canvas p-4 text-foreground sm:grid sm:place-items-center"><div className="flex min-h-[638px] w-full max-w-[900px] overflow-hidden rounded-xl border border-border/80 bg-panel shadow-[0_20px_60px_rgba(74,51,28,0.13)]"><aside className="flex w-48 shrink-0 flex-col border-r border-border/80 bg-sidebar px-3 py-5"><div className="mb-10 flex items-center gap-2 px-2 font-serif text-xl font-semibold"><span className="grid h-7 w-7 place-items-center rounded-full bg-warm text-sm">P</span>Perch</div><nav className="space-y-1" aria-label="Main navigation">{items.map(({ screen: itemScreen, label, icon: Icon }) => <Tooltip.Root key={itemScreen}><Tooltip.Trigger asChild><button onClick={() => onNavigate(itemScreen)} className={cn("relative flex w-full items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-colors", screen === itemScreen ? "text-foreground" : "text-muted-foreground hover:bg-accent/60 hover:text-foreground")}><Icon size={17} strokeWidth={1.8} />{label}{screen === itemScreen && <motion.span layoutId="nav-active" transition={reduceMotion ? { duration: 0 } : { type: "spring", bounce: 0.15, duration: 0.45 }} className="absolute inset-0 -z-0 rounded-md bg-warm/70" />}</button></Tooltip.Trigger><Tooltip.Portal><Tooltip.Content side="right" className="z-50 rounded-md bg-foreground px-2 py-1 text-xs text-primary-foreground shadow-sm">{label}<Tooltip.Arrow className="fill-foreground" /></Tooltip.Content></Tooltip.Portal></Tooltip.Root>)}</nav><p className="mt-auto px-2 text-xs leading-5 text-muted-foreground">A quiet place to keep a little company with your work.</p></aside><ScrollArea.Root className="min-w-0 flex-1 overflow-hidden"><ScrollArea.Viewport className="h-full w-full"><motion.div initial={reduceMotion ? false : { opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0 : 0.22 }} className="min-h-full p-8">{children}</motion.div></ScrollArea.Viewport><ScrollArea.Scrollbar orientation="vertical" className="flex w-2 touch-none p-0.5"><ScrollArea.Thumb className="flex-1 rounded-full bg-border" /></ScrollArea.Scrollbar></ScrollArea.Root></div></main></Tooltip.Provider>;
}
