import { useEffect, useState } from "react";
import { toast } from "sonner";
import type { PastSession, SessionGetTrendsResponse } from "../../../shared/ipc";
import { StatusBar } from "./StatusBar";
import { CategoryBreakdown } from "./CategoryBreakdown";
import { ConfirmDialog } from "./ConfirmDialog";
import { Button, LoadingCard, PageHeader, SectionCard } from "./ui";

const TRENDS_DAYS = 7;
function dayLabel(iso: string): string { return new Date(iso).toLocaleDateString(undefined, { month: "long", day: "numeric", year: "numeric" }); }
function timeLabel(iso: string): string { return new Date(iso).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" }); }
function groupSessions(sessions: PastSession[]): Array<[string, PastSession[]]> { const groups = new Map<string, PastSession[]>(); sessions.forEach((session) => { const key = dayLabel(session.startedAt); groups.set(key, [...(groups.get(key) ?? []), session]); }); return [...groups.entries()]; }

export function PastSessions(): React.JSX.Element {
  const [sessions, setSessions] = useState<PastSession[] | null>(null); const [error, setError] = useState<string | null>(null); const [trends, setTrends] = useState<SessionGetTrendsResponse | null>(null); const [trendsError, setTrendsError] = useState<string | null>(null); const [deleteId, setDeleteId] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { let cancelled = false; window.api.session.getPast({ limit: 20 }).then((res) => !cancelled && setSessions(res.sessions)).catch((err: unknown) => { console.error("[PastSessions] session:getPast failed:", err); if (!cancelled) setError("Past sessions aren't available right now."); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { let cancelled = false; window.api.session.getTrends({ days: TRENDS_DAYS }).then((res) => !cancelled && setTrends(res)).catch((err: unknown) => { console.error("[PastSessions] session:getTrends failed:", err); if (!cancelled) setTrendsError("The weekly snapshot isn't available right now."); }); return () => { cancelled = true; }; }, []);
  const handleDelete = async (): Promise<void> => { if (!deleteId) return; setBusy(true); try { await window.api.session.delete({ sessionId: deleteId }); setSessions((previous) => previous?.filter((session) => session.id !== deleteId) ?? null); setDeleteId(null); toast.success("Session removed."); } catch (err) { console.error("[PastSessions] session:delete failed:", err); toast.error("That session couldn't be removed right now."); } finally { setBusy(false); } };
  return <div className="mx-auto max-w-2xl space-y-6"><PageHeader eyebrow="Sessions" title="A little recent history" description="A simple record of the time you asked Perch to keep an eye on." />{trendsError && <p className="text-sm text-destructive">{trendsError}</p>}{trends ? trends.sessionCount > 0 && <SectionCard className="space-y-4"><div className="flex items-baseline justify-between"><h2 className="font-serif text-xl font-semibold">This week</h2><p className="text-xs text-muted-foreground">{trends.sessionCount} session{trends.sessionCount === 1 ? "" : "s"} in the last {TRENDS_DAYS} days</p></div><StatusBar onTaskSeconds={trends.onTaskSeconds} distractedSeconds={trends.distractedSeconds} ambiguousSeconds={trends.ambiguousSeconds} /><CategoryBreakdown categories={trends.categoryBreakdown} /></SectionCard> : <LoadingCard />}{error && <p className="text-sm text-destructive">{error}</p>}{!error && sessions === null && <LoadingCard />}{sessions?.length === 0 && <SectionCard><p className="font-serif text-lg font-semibold">No sessions yet</p><p className="mt-1 text-sm text-muted-foreground">Start a session when you want a record to return to.</p></SectionCard>}{sessions && sessions.length > 0 && <div className="space-y-6">{groupSessions(sessions).map(([date, entries]) => <section key={date} className="space-y-2"><h2 className="px-1 text-xs font-semibold uppercase tracking-[0.14em] text-clay">{date}</h2><div className="space-y-2">{entries.map((session) => <SectionCard key={session.id} className="space-y-3 py-4"><div className="flex items-start justify-between gap-4"><div><h3 className="text-sm font-semibold">{session.task}</h3><p className="mt-1 text-xs text-muted-foreground">Started at {timeLabel(session.startedAt)}</p></div><Button variant="quiet" className="min-h-0 px-2 py-1 text-xs hover:text-destructive" disabled={busy} onClick={() => setDeleteId(session.id)}>Delete</Button></div>{session.onTaskSeconds !== undefined ? <><StatusBar onTaskSeconds={session.onTaskSeconds} distractedSeconds={session.distractedSeconds ?? 0} ambiguousSeconds={session.ambiguousSeconds ?? 0} />{session.categoryBreakdown && <CategoryBreakdown categories={session.categoryBreakdown} />}</> : <div className="space-y-2 text-sm text-muted-foreground">{session.summary && <p>{session.summary}</p>}{session.nextSteps?.length ? <ul className="list-inside list-disc space-y-1">{session.nextSteps.map((step, index) => <li key={index}>{step}</li>)}</ul> : null}</div>}</SectionCard>)}</div></section>)}</div>}<ConfirmDialog open={deleteId !== null} onOpenChange={(open) => !open && !busy && setDeleteId(null)} title="Remove this session?" description="This removes the saved session from your history. It can’t be restored." confirmLabel="Remove session" busy={busy} onConfirm={() => void handleDelete()} /></div>;
}
