import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Button, Input, PageHeader, SectionCard, Textarea } from "./ui";

interface Props { task: string; onTaskChange: (value: string) => void; distractions: string; onDistractionsChange: (value: string) => void; approved: string; onApprovedChange: (value: string) => void; onStarted: (sessionId: string, startedAt: string, sessionTask: string) => void; }

export function SessionSetup({ task, onTaskChange, distractions, onDistractionsChange, approved, onApprovedChange, onStarted }: Props): React.JSX.Element {
  const [loading, setLoading] = useState(false);
  const [mascot, setMascot] = useState<string | null>(null);
  const canStart = task.trim().length > 0 && distractions.trim().length > 0 && approved.trim().length > 0;
  useEffect(() => { window.api.mascot.getActive().then((active) => setMascot(active?.calm ?? null)).catch(() => setMascot(null)); }, []);
  const handleStart = async (): Promise<void> => { if (!canStart) return; setLoading(true); try { const sessionTask = task.trim(); const distractionList = distractions.split(",").map((s) => s.trim()).filter(Boolean); const approvedList = approved.split(",").map((s) => s.trim()).filter(Boolean); const { sessionId, startedAt } = await window.api.session.start({ task: sessionTask, distractionList, approvedList }); onTaskChange(""); onDistractionsChange(""); onApprovedChange(""); onStarted(sessionId, startedAt, sessionTask); } catch (err) { console.error("[SessionSetup] session:start failed:", err); toast.error("The session couldn't start. Check the app logs and try again."); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-2xl space-y-7"><PageHeader eyebrow="Start" title="What are you working on?" description="Set a little context for this session. Perch will use these details to understand what belongs here." /><SectionCard className="space-y-3"><label htmlFor="task" className="text-sm font-medium">Your task</label><Textarea id="task" rows={4} placeholder="Describe what you want to spend time on" value={task} onChange={(e) => onTaskChange(e.target.value)} disabled={loading} required /></SectionCard><SectionCard className="space-y-5"><div><h2 className="font-serif text-xl font-semibold">Session details</h2><p className="mt-1 text-sm text-muted-foreground">Add a few comma-separated keywords for both lists. These details are required for each session.</p></div><div className="space-y-2"><label htmlFor="distractions" className="text-sm font-medium">Anything you want to avoid?</label><Input id="distractions" placeholder="youtube, reddit, twitter" value={distractions} onChange={(e) => onDistractionsChange(e.target.value)} disabled={loading} required /></div><div className="space-y-2"><label htmlFor="approved" className="text-sm font-medium">Approved keywords or sites</label><Input id="approved" placeholder="docs.python.org, linear.app, figma" value={approved} onChange={(e) => onApprovedChange(e.target.value)} disabled={loading} required /></div></SectionCard><div className="flex items-center justify-between gap-5 rounded-lg bg-warm/35 p-4"><div className="flex items-center gap-3">{mascot ? <img src={mascot} alt="Your selected mascot" className="h-12 w-12 rounded-md object-contain" style={{ imageRendering: "pixelated" }} /> : <div className="grid h-12 w-12 place-items-center rounded-md bg-warm font-serif text-lg">P</div>}<p className="text-sm leading-5 text-muted-foreground">Your mascot will keep you company during the session.</p></div><Button className="shrink-0" disabled={!canStart || loading} onClick={() => void handleStart()}>{loading ? "Starting…" : "Start session"}</Button></div></div>;
}
